version: '3.8'

services:
  steam-ish:
    image: sugoi13/steam-ish:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - BASE_URL={BASE_URL}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - /home/DATA/AppData/steam-ish/logs:/usr/src/app/logs
    network_mode: bridge
    container_name: steam-ish